groups:
- name: alerts
  rules:
  - alert: Beamevents down
    expr: up{job="beamevents"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      title: beamevents {{ $labels.instance }} is down
      description: Failed to scrape {{ $labels.job }} on {{ $labels.instance }} for more than 3 minutes. Node seems down.