# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mysql-config
# data:
#   my.cnf: |
#     [mysqld]
#     datadir=/var/lib/mysql
#     socket=/var/lib/mysql/mysql.sock
#     skip_ssl=1
# ---
apiVersion: v1
kind: Service
metadata:
  name: mysql8
spec:
  selector:
    app: mysql8
  type: NodePort
  ports:
    - name: mysql8
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30011
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql8
spec:
  selector:
    matchLabels:
      app: mysql8
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
        - name: mysql8
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - name: mysql8
              containerPort: 3306
          volumeMounts:
            # - name: mysql-config
            #   mountPath: /etc/mysql/conf.d/my.cnf
            #   subPath: my.cnf
            - name: mysql8-storage
              mountPath: /var/lib/mysql8
      volumes:
        # - name: mysql-config
        #   configMap:
        #     name: mysql-config
        #     items:
        #     - key: my.cnf
        #       path: my.cnf
        - name: mysql8-storage
          persistentVolumeClaim:
            claimName: mysql8-pvc
