apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql8-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/eric/volumes/mysql8
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql8-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
