version: '3' 

volumes:
  postgres_data:
  kafka_data:
  zookeeper_data:

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - labs
    volumes:
      - ./data/mongo:/data
    deploy:
      resources:
        limits:
          memory: 500m
 
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    hostname: mongo_express
    restart: unless-stopped
    ports:
      - 28081:8081
    networks:
      - labs
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    deploy:
      resources:
        limits:
          memory: 200m

networks:
  labs:
    driver: bridge