version: '3.7'

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aluno
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno123
    volumes:
      - mysql_data:/var/lib/mysql
      
