version: '3.8'

services:
  ldap:
    image: osixia/openldap:latest
    container_name: ldap_server
    environment:
      LDAP_ORGANISATION: "Minha Empresa"
      LDAP_DOMAIN: "minhaempresa.local"
      LDAP_ADMIN_PASSWORD: "adminsenha"
    ports:
      - "389:389"   # Porta LDAP
      - "636:636"   # Porta LDAPs (opcional)
    restart: unless-stopped
    volumes:
      - ./ldap-data:/var/lib/ldap
      - ./ldap-config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap_admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - ldap
