version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:v21.1.0
    command: start-single-node --insecure --advertise-addr=cockroachdb
    ports:
      - "26257:26257"
      - "38080:8080"
    volumes:
      - cockroachdb_data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://cockroachdb:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cockroachdb_data:
