version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    hostname: cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save "" --appendonly no
    volumes: 
      - cache:/data
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'
    networks:
      - labs

networks:
  labs:
    driver: bridge

volumes:
  cache:
    driver: local